site_name: Hackintosh Documents
theme:
    name: material
    hljs_languages:
        - yaml
plugins:
    - search: {}
    # - encryptcontent:
    #       # global_password: 'unilap'
    #       remember_password: True
    #       default_expire_dalay: 30
    #       summary: 'Welcome'
    #       placeholder: 'Enter your partner code here and press ENTER.'
    #       decryption_failure_message: 'Failure, your partner code is incorrect.'
    #       encryption_info_message: 'Please contact administrator to get necessary access.'

markdown_extensions:
    - smarty
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
        permalink: True
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  generator: false